FUNCTION(LINK_THIRDPARTY_GLUT project)
  TARGET_LINK_LIBRARIES(${project} ${OPENGL_LIBRARIES} ${GLUT_glut_LIBRARY})
ENDFUNCTION(LINK_THIRDPARTY_GLUT)

FUNCTION(LINK_THIRDPARTY_TICPP project)
    TARGET_LINK_LIBRARIES(${project} ticpp)
ENDFUNCTION(LINK_THIRDPARTY_TICPP)
