// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define RTQL8_ROOT_PATH "/Users/karenliu/Research/RTQL8/"
#define RTQL8_DATA_PATH "/Users/karenliu/Research/RTQL8/data/"

#endif // ifndef UTILS_PATHS_H
